### ISSUE TITLE
Open TablePlus button doesn't work if /tmp/mysql.sock doesn't exist

### ISSUE THREAD

**Issue by bgturner** [aubreypwd/local-tableplus#11]
This is related to #9 , so if we want to merge these two issues we can. 

While doing QA of the `1.0.3` version, I noticed that the button didn't respond. Looking at the console errors within Local, it looks like if the `/tmp/mysql.sock` doesn't exist, the button doesn't work.

The specific error looks like:

```
Uncaught Error: ENOENT: no such file or directory, unlink '/tmp/mysql.sock'
```

![image](https://user-images.githubusercontent.com/299432/112872418-38982300-9075-11eb-9272-c775e789ec4a.png)

**Comment by aubreypwd** [comment]
![image](https://user-images.githubusercontent.com/1753298/112873779-55d1ef00-907f-11eb-9806-6f264f8bdbb7.png)

I can validate this, and it is separate from #9 since the file not existing should create the file....

**Comment by aubreypwd** [comment]
https://github.com/aubreypwd/local-tableplus/releases/tag/v1.0.4 Thanks @bgturner hopefully this fixes the issue you found...

**Comment by bgturner** [comment]
Just tested and looks good! Thanks for the quick fix!
