### ISSUE TITLE
Fix issue when site names have spaces

### ISSUE THREAD

**Issue by aubreypwd** [aubreypwd/local-tableplus#12]
See https://github.com/aubreypwd/local-tableplus/issues/9#issuecomment-834718596

---

> ...After several tests, I think I found the issue. You may need to process the site data on [this line](https://github.com/aubreypwd/local-tableplus/blob/master/src/TablePlus.js#L130) for cases in which the name of the site contains more than one word.
>
>You can see some tests [here](https://monosnap.com/file/OqpHdCJ4bpp8fPkGu4GLximDE7Np4j)
>
>The good news is that the original issue is fixed in `v1.0.5-beta.3`
>Thanks

**Comment by aubreypwd** [comment]
- [ ] We probably need to escape https://github.com/aubreypwd/local-tableplus/blob/master/src/TablePlus.js#L130 with `\`'s

**Comment by rodrigo-arias** [comment]
I can confirm that this is fixed. Thank you
