### ISSUE TITLE
Update TablePlus Addons Page with latest version

### ISSUE THREAD

**Issue by aubreypwd** [aubreypwd/local-tableplus#15]
https://github.com/aubreypwd/localwp-tableplus/releases/tag/v1.1.0 was release days ago, based off feedback from #13 (still waiting for confirmation that the actual release works). 

But once we get a confirmation I need to update the LocalWP community that a new release is available.

- [ ] Also document release update process in Wiki

**Comment by bgturner** [comment]
I was cycling through the various Addons that are published in Local and noticed the new release [v1.1.0](https://github.com/aubreypwd/localwp-tableplus/releases/tag/v1.1.0). I tested this on the upcoming Local Beta 8.0.0 using an M1 mac: everything looks good!

I've added it to our CDN and marked it as tested through 8.0.0.

<img width="1003" alt="Screenshot 2023-10-02 at 10 38 07 AM" src="https://github.com/aubreypwd/localwp-tableplus/assets/299432/bddd2244-1f01-4384-a83e-8c86896a879a">
