### ISSUE TITLE
Support TablePlus from Setapp

### ISSUE THREAD

**Issue by alexclst** [aubreypwd/local-tableplus#16]
I have TablePlus installed via Setapp, so it is not at `/Applications/TablePlus.app`, but rather at `/Applications/Setapp/TablePlus.app`. As such, it does not allow me to use this add on at all, as it never thinks that I have TablePlus installed.

**Comment by aubreypwd** [comment]
We [already](https://github.com/aubreypwd/localwp-tableplus/blob/436444cbdbd6b29020f8fb7d7961324b994c5c58/src/TablePlus.js#L297) have support for using TablePlus installed via SetApp, are you sure it's registered to handle `mysql://` URI's, or have you tried updating the addon?

**Comment by aubreypwd** [comment]
@alexclst Just following up here before I close this....

**Comment by alexclst** [comment]
@aubreypwd I never saw the first reply... Guess it got spammed in my email. Anyway, an update seems to have fixed it.
