### ISSUE TITLE
"Open Tableplus" button/link is not active in Local

### ISSUE THREAD

**Issue by kalonya** [aubreypwd/local-tableplus#20]
It happens when the app is in the Applications/Setapp folder. When I move it to the Applications folder, it works.

![CleanShot 2022-12-14 at 14 31 32@2x](https://user-images.githubusercontent.com/16854238/207584393-a43a1c18-1ca3-4151-8dfa-c8e706a894d0.jpg)

![CleanShot 2022-12-14 at 14 32 49@2x](https://user-images.githubusercontent.com/16854238/207584502-b68a988e-170b-4e1a-ac90-b2e77017c46d.jpg)

**Comment by aubreypwd** [comment]
This addon does [have support for Setapp](https://github.com/aubreypwd/localwp-tableplus/blob/436444cbdbd6b29020f8fb7d7961324b994c5c58/src/TablePlus.js#L298), have you updated your addon in a while?

**Comment by kalonya** [comment]
Oh, sorry. The add-ons section of Local installs v1.0.5. I downloaded the latest release from here and overwrote the current one manually. Now it works fine. 🙂
