### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by Oceas** [aubreypwd/local-tableplus#3]
Got the following install error when installing from .tgz

![image](https://user-images.githubusercontent.com/17047900/89786046-51a19300-dae9-11ea-97e1-4f0a0e71d20e.png)

**Comment by aubreypwd** [comment]
FYI @Oceas and I were able to solve this by removing a previous symlink in `~/Library/Application Support/Local/addons`. Installer was fully tested and working!
