### ISSUE TITLE
Tab not appearing in latest Local 5.9.3+5100

### ISSUE THREAD

**Issue by colorful-tones** [aubreypwd/local-tableplus#7]
I followed [Install](https://github.com/aubreypwd/local-tableplus#install) instructions from `README`, but tab does not appear after restarting Local. Just seeing the usual: "Open Adminer" and "Open Sequel Pro"

```
Local 5.9.3+5100
macOS 10.15.7
```

**Comment by aubreypwd** [comment]
Hmm, interesting. I assume you enabled it?

**Comment by colorful-tones** [comment]
Yes, the TablePlus add-on was enabled.

I've since updated Local to the latest, and the tab is still not showing.

```
Local 5.9.7+5156
macOS 10.15.7
```

<img width="1189" alt="Screen Shot 2020-12-28 at 10 51 01 AM" src="https://user-images.githubusercontent.com/405912/103227008-5f6e7e00-48fb-11eb-9491-e9e5ac5daa7c.png">
<img width="821" alt="Screen Shot 2020-12-28 at 10 51 28 AM" src="https://user-images.githubusercontent.com/405912/103227010-60071480-48fb-11eb-8554-7f32cfec82b6.png">

**Comment by aubreypwd** [comment]
@colorful-tones Have you tried installing it via the addon tab in Local?

**Comment by colorful-tones** [comment]
I'm gonna go ahead and close this out. I do not have time to re-test and have upgraded mac OS and Local several times since. Probably just user error on my end? 🤷 

Thanks @aubreypwd
